### PR TITLE
wczblackman: add checking to foo.py

### PR DESCRIPTION
**Pull request by wczblackman**
wczmatthew: I added checking to foo.py, please review, thanks.

### CODE REVIEW

**Comment by wczmatthew** [comment]
Please use 'return -1' instead at L8.

**Comment by wczblackman** [comment]
Done. Please check again.

**Comment by wczmatthew** [comment]
Hi Daxiang! If you get to the final version of the pull, can you please squash the commits into a single one and let me know so I can check it?

**Comment by wczblackman** [comment]
The two commits are squashed into a single one now, please check again.

**Pull request merged**
